[package]
name = "my_token"
version = "0.1.0"
edition = "2024"

[dependencies]
ethers = { version = "2.0", features = ["abigen"] }
eyre = "0.6"
tokio = { version = "1.0", features = ["full"] }
rand = "0.8"
